#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 ursa.nz <code@ursa.nz>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Measure the translations overlay's coverage per language and gate it with regression floors. Writes
# the committed report at tests/omw-coverage-report.txt and exits nonzero if any language falls below
# its floor or the total falls below the overall floor, so a data bump that quietly drops coverage
# fails the gate. The figures come from the overlay's own provenance header, which the producer writes
# as it builds the file. A language with no floor below is reported but not gated, so a newly added
# component does not fail the gate until a floor is set for it.
#
# Usage: tests/coverage-omw.sh         # check against the floors and rewrite the report
#        tests/coverage-omw.sh --check # check only, do not rewrite the report

set -euo pipefail

here=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
overlay="$here/overlays/omw.onym.zst"
report="$here/tests/omw-coverage-report.txt"

# The lowest synset coverage each language may carry before this gate fails, below the current figures
# with headroom for ordinary churn in the OMW components, plus the overall floor on keyed synsets.
declare -A floor=([id]=34000 [it]=31000 [pt]=39000)
total_floor=60000

[ -s "$overlay" ] || { echo "coverage-omw: missing $overlay" >&2; exit 1; }

# The overlay is vendored compressed; decompress it once to read its provenance header.
plain=$(mktemp)
trap 'rm -f "$plain"' EXIT INT TERM
zstd -dc -- "$overlay" > "$plain"

edition=$(head -n1 "$here/base/VERSION" 2>/dev/null || echo "unknown")

header_value() { grep -m1 "^ $1:" "$plain" | sed "s/^ $1: *//"; }
base_ili=$(header_value 'base-synsets-with-ili')
keyed=$(header_value 'keyed-synsets')
case "$base_ili$keyed" in
  *[!0-9]* | '') echo "coverage-omw: could not read synset counts from $overlay header" >&2; exit 1 ;;
esac

fail=0
rows=""
# The languages come from the overlay's own legend, so the report follows whatever is shipped.
for code in $(grep '^ lang ' "$plain" | awk '{print $2}'); do
  name=$(grep -m1 "^ lang $code " "$plain" | sed "s/^ lang $code //")
  count=$(grep -m1 "^ coverage $code:" "$plain" | sed "s/^ coverage $code: *//")
  case "$count" in *[!0-9]* | '') count=0 ;; esac
  f=${floor[$code]:-0}
  pct=$(awk -v c="$count" -v b="$base_ili" 'BEGIN { printf "%.1f", b ? 100 * c / b : 0 }')
  rows+=$(printf '  %-18s %7s synsets  %5s%%  floor %s\n' "$name ($code)" "$count" "$pct" "$f")$'\n'
  if [ "$f" -gt 0 ] && [ "$count" -lt "$f" ]; then
    echo "coverage-omw: $code below floor ($count < $f)" >&2
    fail=1
  fi
done

if [ "$keyed" -lt "$total_floor" ]; then
  echo "coverage-omw: keyed synsets below floor ($keyed < $total_floor)" >&2
  fail=1
fi

if [ "${1:-}" != "--check" ]; then
  {
    echo "Translations overlay coverage on the $edition base."
    echo
    echo "  base synsets with an ILI: $base_ili"
    echo "  synsets with a translation: $keyed   (overall floor $total_floor)"
    echo
    printf '%s' "$rows"
    echo
    echo "Per language, the synsets that carry at least one word in that language, and the percentage"
    echo "of the joinable universe (synsets with an ILI). Generated by tests/coverage-omw.sh from the"
    echo "overlay's provenance header. The floors are the regression gate: a data bump that drops any"
    echo "language below its floor, or the total below the overall floor, fails this script."
  } > "$report"
  echo "wrote $report"
fi

echo "coverage-omw: $keyed keyed synsets (floor $total_floor)"
[ "$fail" -eq 0 ] || exit 1
