#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 ursa.nz <code@ursa.nz>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Measure overlay coverage against the base and gate it with a regression floor. Writes the committed
# report at tests/coverage-report.txt and exits nonzero if coverage falls below the floor, so a data
# bump that quietly drops coverage fails the gate. The figures come from the overlay's own provenance
# header, which the producer writes as it builds the file.
#
# Usage: tests/coverage.sh         # check against the floor and rewrite the report
#        tests/coverage.sh --check # check only, do not rewrite the report

set -euo pipefail

here=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
overlay="$here/overlays/etym.onym"
report="$here/tests/coverage-report.txt"

# The lowest coverage a data bump may carry before this gate fails. Below the current figure, with
# headroom for ordinary churn in the Wiktionary source.
floor_pct=43.0

[ -s "$overlay" ] || { echo "coverage: missing $overlay" >&2; exit 1; }

# The base edition the report names, read from the first line of base/VERSION.
edition=$(head -n1 "$here/base/VERSION" 2>/dev/null || echo "unknown")

# The header lines lead with a space and read "key: value"; pull the two lemma counts.
header_value() { grep -m1 "^ $1:" "$overlay" | sed "s/^ $1: *//"; }
wordnet_lemmas=$(header_value 'wordnet-lemmas')
matched_lemmas=$(header_value 'matched-lemmas')

case "$wordnet_lemmas$matched_lemmas" in
  *[!0-9]* | '') echo "coverage: could not read lemma counts from $overlay header" >&2; exit 1 ;;
esac

pct=$(awk -v m="$matched_lemmas" -v w="$wordnet_lemmas" 'BEGIN { printf "%.1f", w ? 100 * m / w : 0 }')

below=$(awk -v p="$pct" -v f="$floor_pct" 'BEGIN { print (p < f) ? 1 : 0 }')

if [ "${1:-}" != "--check" ]; then
  cat > "$report" <<EOF
Etymology overlay coverage on the $edition base.

  matched lemmas:  $matched_lemmas
  WordNet lemmas:  $wordnet_lemmas
  coverage:        $pct%
  floor:           $floor_pct%

Generated by tests/coverage.sh from the overlay's provenance header. The floor is the regression
gate: a data bump that drops coverage below it fails tests/coverage.sh.
EOF
  echo "wrote $report"
fi

echo "coverage: $pct% (floor $floor_pct%)"
if [ "$below" -eq 1 ]; then
  echo "coverage: below floor" >&2
  exit 1
fi
